# Multi Layer Perceptron
First we load the data that we will be using.<br>
- Data : Wisconsin Breat Cancer<br>
https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/<br>       
Data can be downloaded from :       <br>
https://archive.ics.uci.edu/ml/machine-learning-databases/<br>
breast-cancer-wisconsin/breast-cancer-wisconsin.data  <br>

Sample code number            id number <br>
Clump Thickness               1 - 10 <br>
Uniformity of Cell Size       1 - 10 <br>
Uniformity of Cell Shape      1 - 10 <br>
Marginal Adhesion             1 - 10 <br>
Single Epithelial Cell Size   1 - 10 <br>
Bare Nuclei                   1 - 10 <br>
Bland Chromatin               1 - 10 <br>
Normal Nucleoli               1 - 10 <br>
Mitoses                       1 - 10 <br>
Class:                        (2 for benign, 4 for malignant)<br>

In [2]:
data =['1000025,5,1,1,1,2,1,3,1,1,2\n',
 '1002945,5,4,4,5,7,10,3,2,1,2\n',
 '1015425,3,1,1,1,2,2,3,1,1,2\n',
 '1016277,6,8,8,1,3,4,3,7,1,2\n',
 '1017023,4,1,1,3,2,1,3,1,1,2\n',
 '1017122,8,10,10,8,7,10,9,7,1,4\n',
 '1018099,1,1,1,1,2,10,3,1,1,2\n',
 '1018561,2,1,2,1,2,1,3,1,1,2\n',
 '1033078,2,1,1,1,2,1,1,1,5,2\n',
 '1033078,4,2,1,1,2,1,2,1,1,2\n',
 '1035283,1,1,1,1,1,1,3,1,1,2\n',
 '1036172,2,1,1,1,2,1,2,1,1,2\n',
 '1041801,5,3,3,3,2,3,4,4,1,4\n',
 '1043999,1,1,1,1,2,3,3,1,1,2\n',
 '1044572,8,7,5,10,7,9,5,5,4,4\n',
 '1047630,7,4,6,4,6,1,4,3,1,4\n',
 '1048672,4,1,1,1,2,1,2,1,1,2\n',
 '1049815,4,1,1,1,2,1,3,1,1,2\n',
 '1050670,10,7,7,6,4,10,4,1,2,4\n',
 '1050718,6,1,1,1,2,1,3,1,1,2\n',
 '1054590,7,3,2,10,5,10,5,4,4,4\n',
 '1054593,10,5,5,3,6,7,7,10,1,4\n',
 '1056784,3,1,1,1,2,1,2,1,1,2\n',
 '1057013,8,4,5,1,2,?,7,3,1,4\n',
 '1059552,1,1,1,1,2,1,3,1,1,2\n',
 '1065726,5,2,3,4,2,7,3,6,1,4\n',
 '1066373,3,2,1,1,1,1,2,1,1,2\n',
 '1066979,5,1,1,1,2,1,2,1,1,2\n',
 '1067444,2,1,1,1,2,1,2,1,1,2\n',
 '1070935,1,1,3,1,2,1,1,1,1,2\n',
 '1070935,3,1,1,1,1,1,2,1,1,2\n',
 '1071760,2,1,1,1,2,1,3,1,1,2\n',
 '1072179,10,7,7,3,8,5,7,4,3,4\n',
 '1074610,2,1,1,2,2,1,3,1,1,2\n',
 '1075123,3,1,2,1,2,1,2,1,1,2\n',
 '1079304,2,1,1,1,2,1,2,1,1,2\n',
 '1080185,10,10,10,8,6,1,8,9,1,4\n',
 '1081791,6,2,1,1,1,1,7,1,1,2\n',
 '1084584,5,4,4,9,2,10,5,6,1,4\n',
 '1091262,2,5,3,3,6,7,7,5,1,4\n',
 '1096800,6,6,6,9,6,?,7,8,1,2\n',
 '1099510,10,4,3,1,3,3,6,5,2,4\n',
 '1100524,6,10,10,2,8,10,7,3,3,4\n',
 '1102573,5,6,5,6,10,1,3,1,1,4\n',
 '1103608,10,10,10,4,8,1,8,10,1,4\n',
 '1103722,1,1,1,1,2,1,2,1,2,2\n',
 '1105257,3,7,7,4,4,9,4,8,1,4\n',
 '1105524,1,1,1,1,2,1,2,1,1,2\n',
 '1106095,4,1,1,3,2,1,3,1,1,2\n',
 '1106829,7,8,7,2,4,8,3,8,2,4\n',
 '1108370,9,5,8,1,2,3,2,1,5,4\n',
 '1108449,5,3,3,4,2,4,3,4,1,4\n',
 '1110102,10,3,6,2,3,5,4,10,2,4\n',
 '1110503,5,5,5,8,10,8,7,3,7,4\n',
 '1110524,10,5,5,6,8,8,7,1,1,4\n',
 '1111249,10,6,6,3,4,5,3,6,1,4\n',
 '1112209,8,10,10,1,3,6,3,9,1,4\n',
 '1113038,8,2,4,1,5,1,5,4,4,4\n',
 '1113483,5,2,3,1,6,10,5,1,1,4\n',
 '1113906,9,5,5,2,2,2,5,1,1,4\n',
 '1115282,5,3,5,5,3,3,4,10,1,4\n',
 '1115293,1,1,1,1,2,2,2,1,1,2\n',
 '1116116,9,10,10,1,10,8,3,3,1,4\n',
 '1116132,6,3,4,1,5,2,3,9,1,4\n',
 '1116192,1,1,1,1,2,1,2,1,1,2\n',
 '1116998,10,4,2,1,3,2,4,3,10,4\n',
 '1117152,4,1,1,1,2,1,3,1,1,2\n',
 '1118039,5,3,4,1,8,10,4,9,1,4\n',
 '1120559,8,3,8,3,4,9,8,9,8,4\n',
 '1121732,1,1,1,1,2,1,3,2,1,2\n',
 '1121919,5,1,3,1,2,1,2,1,1,2\n',
 '1123061,6,10,2,8,10,2,7,8,10,4\n',
 '1124651,1,3,3,2,2,1,7,2,1,2\n',
 '1125035,9,4,5,10,6,10,4,8,1,4\n',
 '1126417,10,6,4,1,3,4,3,2,3,4\n',
 '1131294,1,1,2,1,2,2,4,2,1,2\n',
 '1132347,1,1,4,1,2,1,2,1,1,2\n',
 '1133041,5,3,1,2,2,1,2,1,1,2\n',
 '1133136,3,1,1,1,2,3,3,1,1,2\n',
 '1136142,2,1,1,1,3,1,2,1,1,2\n',
 '1137156,2,2,2,1,1,1,7,1,1,2\n',
 '1143978,4,1,1,2,2,1,2,1,1,2\n',
 '1143978,5,2,1,1,2,1,3,1,1,2\n',
 '1147044,3,1,1,1,2,2,7,1,1,2\n',
 '1147699,3,5,7,8,8,9,7,10,7,4\n',
 '1147748,5,10,6,1,10,4,4,10,10,4\n',
 '1148278,3,3,6,4,5,8,4,4,1,4\n',
 '1148873,3,6,6,6,5,10,6,8,3,4\n',
 '1152331,4,1,1,1,2,1,3,1,1,2\n',
 '1155546,2,1,1,2,3,1,2,1,1,2\n',
 '1156272,1,1,1,1,2,1,3,1,1,2\n',
 '1156948,3,1,1,2,2,1,1,1,1,2\n',
 '1157734,4,1,1,1,2,1,3,1,1,2\n',
 '1158247,1,1,1,1,2,1,2,1,1,2\n',
 '1160476,2,1,1,1,2,1,3,1,1,2\n',
 '1164066,1,1,1,1,2,1,3,1,1,2\n',
 '1165297,2,1,1,2,2,1,1,1,1,2\n',
 '1165790,5,1,1,1,2,1,3,1,1,2\n',
 '1165926,9,6,9,2,10,6,2,9,10,4\n',
 '1166630,7,5,6,10,5,10,7,9,4,4\n',
 '1166654,10,3,5,1,10,5,3,10,2,4\n',
 '1167439,2,3,4,4,2,5,2,5,1,4\n',
 '1167471,4,1,2,1,2,1,3,1,1,2\n',
 '1168359,8,2,3,1,6,3,7,1,1,4\n',
 '1168736,10,10,10,10,10,1,8,8,8,4\n',
 '1169049,7,3,4,4,3,3,3,2,7,4\n',
 '1170419,10,10,10,8,2,10,4,1,1,4\n',
 '1170420,1,6,8,10,8,10,5,7,1,4\n',
 '1171710,1,1,1,1,2,1,2,3,1,2\n',
 '1171710,6,5,4,4,3,9,7,8,3,4\n',
 '1171795,1,3,1,2,2,2,5,3,2,2\n',
 '1171845,8,6,4,3,5,9,3,1,1,4\n',
 '1172152,10,3,3,10,2,10,7,3,3,4\n',
 '1173216,10,10,10,3,10,8,8,1,1,4\n',
 '1173235,3,3,2,1,2,3,3,1,1,2\n',
 '1173347,1,1,1,1,2,5,1,1,1,2\n',
 '1173347,8,3,3,1,2,2,3,2,1,2\n',
 '1173509,4,5,5,10,4,10,7,5,8,4\n',
 '1173514,1,1,1,1,4,3,1,1,1,2\n',
 '1173681,3,2,1,1,2,2,3,1,1,2\n',
 '1174057,1,1,2,2,2,1,3,1,1,2\n',
 '1174057,4,2,1,1,2,2,3,1,1,2\n',
 '1174131,10,10,10,2,10,10,5,3,3,4\n',
 '1174428,5,3,5,1,8,10,5,3,1,4\n',
 '1175937,5,4,6,7,9,7,8,10,1,4\n',
 '1176406,1,1,1,1,2,1,2,1,1,2\n',
 '1176881,7,5,3,7,4,10,7,5,5,4\n',
 '1177027,3,1,1,1,2,1,3,1,1,2\n',
 '1177399,8,3,5,4,5,10,1,6,2,4\n',
 '1177512,1,1,1,1,10,1,1,1,1,2\n',
 '1178580,5,1,3,1,2,1,2,1,1,2\n',
 '1179818,2,1,1,1,2,1,3,1,1,2\n',
 '1180194,5,10,8,10,8,10,3,6,3,4\n',
 '1180523,3,1,1,1,2,1,2,2,1,2\n',
 '1180831,3,1,1,1,3,1,2,1,1,2\n',
 '1181356,5,1,1,1,2,2,3,3,1,2\n',
 '1182404,4,1,1,1,2,1,2,1,1,2\n',
 '1182410,3,1,1,1,2,1,1,1,1,2\n',
 '1183240,4,1,2,1,2,1,2,1,1,2\n',
 '1183246,1,1,1,1,1,?,2,1,1,2\n',
 '1183516,3,1,1,1,2,1,1,1,1,2\n',
 '1183911,2,1,1,1,2,1,1,1,1,2\n',
 '1183983,9,5,5,4,4,5,4,3,3,4\n',
 '1184184,1,1,1,1,2,5,1,1,1,2\n',
 '1184241,2,1,1,1,2,1,2,1,1,2\n',
 '1184840,1,1,3,1,2,?,2,1,1,2\n',
 '1185609,3,4,5,2,6,8,4,1,1,4\n',
 '1185610,1,1,1,1,3,2,2,1,1,2\n',
 '1187457,3,1,1,3,8,1,5,8,1,2\n',
 '1187805,8,8,7,4,10,10,7,8,7,4\n',
 '1188472,1,1,1,1,1,1,3,1,1,2\n',
 '1189266,7,2,4,1,6,10,5,4,3,4\n',
 '1189286,10,10,8,6,4,5,8,10,1,4\n',
 '1190394,4,1,1,1,2,3,1,1,1,2\n',
 '1190485,1,1,1,1,2,1,1,1,1,2\n',
 '1192325,5,5,5,6,3,10,3,1,1,4\n',
 '1193091,1,2,2,1,2,1,2,1,1,2\n',
 '1193210,2,1,1,1,2,1,3,1,1,2\n',
 '1193683,1,1,2,1,3,?,1,1,1,2\n',
 '1196295,9,9,10,3,6,10,7,10,6,4\n',
 '1196915,10,7,7,4,5,10,5,7,2,4\n',
 '1197080,4,1,1,1,2,1,3,2,1,2\n',
 '1197270,3,1,1,1,2,1,3,1,1,2\n',
 '1197440,1,1,1,2,1,3,1,1,7,2\n',
 '1197510,5,1,1,1,2,?,3,1,1,2\n',
 '1197979,4,1,1,1,2,2,3,2,1,2\n',
 '1197993,5,6,7,8,8,10,3,10,3,4\n',
 '1198128,10,8,10,10,6,1,3,1,10,4\n',
 '1198641,3,1,1,1,2,1,3,1,1,2\n',
 '1199219,1,1,1,2,1,1,1,1,1,2\n',
 '1199731,3,1,1,1,2,1,1,1,1,2\n',
 '1199983,1,1,1,1,2,1,3,1,1,2\n',
 '1200772,1,1,1,1,2,1,2,1,1,2\n',
 '1200847,6,10,10,10,8,10,10,10,7,4\n',
 '1200892,8,6,5,4,3,10,6,1,1,4\n',
 '1200952,5,8,7,7,10,10,5,7,1,4\n',
 '1201834,2,1,1,1,2,1,3,1,1,2\n',
 '1201936,5,10,10,3,8,1,5,10,3,4\n',
 '1202125,4,1,1,1,2,1,3,1,1,2\n',
 '1202812,5,3,3,3,6,10,3,1,1,4\n',
 '1203096,1,1,1,1,1,1,3,1,1,2\n',
 '1204242,1,1,1,1,2,1,1,1,1,2\n',
 '1204898,6,1,1,1,2,1,3,1,1,2\n',
 '1205138,5,8,8,8,5,10,7,8,1,4\n',
 '1205579,8,7,6,4,4,10,5,1,1,4\n',
 '1206089,2,1,1,1,1,1,3,1,1,2\n',
 '1206695,1,5,8,6,5,8,7,10,1,4\n',
 '1206841,10,5,6,10,6,10,7,7,10,4\n',
 '1207986,5,8,4,10,5,8,9,10,1,4\n',
 '1208301,1,2,3,1,2,1,3,1,1,2\n',
 '1210963,10,10,10,8,6,8,7,10,1,4\n',
 '1211202,7,5,10,10,10,10,4,10,3,4\n',
 '1212232,5,1,1,1,2,1,2,1,1,2\n',
 '1212251,1,1,1,1,2,1,3,1,1,2\n',
 '1212422,3,1,1,1,2,1,3,1,1,2\n',
 '1212422,4,1,1,1,2,1,3,1,1,2\n',
 '1213375,8,4,4,5,4,7,7,8,2,2\n',
 '1213383,5,1,1,4,2,1,3,1,1,2\n',
 '1214092,1,1,1,1,2,1,1,1,1,2\n',
 '1214556,3,1,1,1,2,1,2,1,1,2\n',
 '1214966,9,7,7,5,5,10,7,8,3,4\n',
 '1216694,10,8,8,4,10,10,8,1,1,4\n',
 '1216947,1,1,1,1,2,1,3,1,1,2\n',
 '1217051,5,1,1,1,2,1,3,1,1,2\n',
 '1217264,1,1,1,1,2,1,3,1,1,2\n',
 '1218105,5,10,10,9,6,10,7,10,5,4\n',
 '1218741,10,10,9,3,7,5,3,5,1,4\n',
 '1218860,1,1,1,1,1,1,3,1,1,2\n',
 '1218860,1,1,1,1,1,1,3,1,1,2\n',
 '1219406,5,1,1,1,1,1,3,1,1,2\n',
 '1219525,8,10,10,10,5,10,8,10,6,4\n',
 '1219859,8,10,8,8,4,8,7,7,1,4\n',
 '1220330,1,1,1,1,2,1,3,1,1,2\n',
 '1221863,10,10,10,10,7,10,7,10,4,4\n',
 '1222047,10,10,10,10,3,10,10,6,1,4\n',
 '1222936,8,7,8,7,5,5,5,10,2,4\n',
 '1223282,1,1,1,1,2,1,2,1,1,2\n',
 '1223426,1,1,1,1,2,1,3,1,1,2\n',
 '1223793,6,10,7,7,6,4,8,10,2,4\n',
 '1223967,6,1,3,1,2,1,3,1,1,2\n',
 '1224329,1,1,1,2,2,1,3,1,1,2\n',
 '1225799,10,6,4,3,10,10,9,10,1,4\n',
 '1226012,4,1,1,3,1,5,2,1,1,4\n',
 '1226612,7,5,6,3,3,8,7,4,1,4\n',
 '1227210,10,5,5,6,3,10,7,9,2,4\n',
 '1227244,1,1,1,1,2,1,2,1,1,2\n',
 '1227481,10,5,7,4,4,10,8,9,1,4\n',
 '1228152,8,9,9,5,3,5,7,7,1,4\n',
 '1228311,1,1,1,1,1,1,3,1,1,2\n',
 '1230175,10,10,10,3,10,10,9,10,1,4\n',
 '1230688,7,4,7,4,3,7,7,6,1,4\n',
 '1231387,6,8,7,5,6,8,8,9,2,4\n',
 '1231706,8,4,6,3,3,1,4,3,1,2\n',
 '1232225,10,4,5,5,5,10,4,1,1,4\n',
 '1236043,3,3,2,1,3,1,3,6,1,2\n',
 '1241232,3,1,4,1,2,?,3,1,1,2\n',
 '1241559,10,8,8,2,8,10,4,8,10,4\n',
 '1241679,9,8,8,5,6,2,4,10,4,4\n',
 '1242364,8,10,10,8,6,9,3,10,10,4\n',
 '1243256,10,4,3,2,3,10,5,3,2,4\n',
 '1270479,5,1,3,3,2,2,2,3,1,2\n',
 '1276091,3,1,1,3,1,1,3,1,1,2\n',
 '1277018,2,1,1,1,2,1,3,1,1,2\n',
 '128059,1,1,1,1,2,5,5,1,1,2\n',
 '1285531,1,1,1,1,2,1,3,1,1,2\n',
 '1287775,5,1,1,2,2,2,3,1,1,2\n',
 '144888,8,10,10,8,5,10,7,8,1,4\n',
 '145447,8,4,4,1,2,9,3,3,1,4\n',
 '167528,4,1,1,1,2,1,3,6,1,2\n',
 '169356,3,1,1,1,2,?,3,1,1,2\n',
 '183913,1,2,2,1,2,1,1,1,1,2\n',
 '191250,10,4,4,10,2,10,5,3,3,4\n',
 '1017023,6,3,3,5,3,10,3,5,3,2\n',
 '1100524,6,10,10,2,8,10,7,3,3,4\n',
 '1116116,9,10,10,1,10,8,3,3,1,4\n',
 '1168736,5,6,6,2,4,10,3,6,1,4\n',
 '1182404,3,1,1,1,2,1,1,1,1,2\n',
 '1182404,3,1,1,1,2,1,2,1,1,2\n',
 '1198641,3,1,1,1,2,1,3,1,1,2\n',
 '242970,5,7,7,1,5,8,3,4,1,2\n',
 '255644,10,5,8,10,3,10,5,1,3,4\n',
 '263538,5,10,10,6,10,10,10,6,5,4\n',
 '274137,8,8,9,4,5,10,7,8,1,4\n',
 '303213,10,4,4,10,6,10,5,5,1,4\n',
 '314428,7,9,4,10,10,3,5,3,3,4\n',
 '1182404,5,1,4,1,2,1,3,2,1,2\n',
 '1198641,10,10,6,3,3,10,4,3,2,4\n',
 '320675,3,3,5,2,3,10,7,1,1,4\n',
 '324427,10,8,8,2,3,4,8,7,8,4\n',
 '385103,1,1,1,1,2,1,3,1,1,2\n',
 '390840,8,4,7,1,3,10,3,9,2,4\n',
 '411453,5,1,1,1,2,1,3,1,1,2\n',
 '320675,3,3,5,2,3,10,7,1,1,4\n',
 '428903,7,2,4,1,3,4,3,3,1,4\n',
 '431495,3,1,1,1,2,1,3,2,1,2\n',
 '432809,3,1,3,1,2,?,2,1,1,2\n',
 '434518,3,1,1,1,2,1,2,1,1,2\n',
 '452264,1,1,1,1,2,1,2,1,1,2\n',
 '456282,1,1,1,1,2,1,3,1,1,2\n',
 '476903,10,5,7,3,3,7,3,3,8,4\n',
 '486283,3,1,1,1,2,1,3,1,1,2\n',
 '486662,2,1,1,2,2,1,3,1,1,2\n',
 '488173,1,4,3,10,4,10,5,6,1,4\n',
 '492268,10,4,6,1,2,10,5,3,1,4\n',
 '508234,7,4,5,10,2,10,3,8,2,4\n',
 '527363,8,10,10,10,8,10,10,7,3,4\n',
 '529329,10,10,10,10,10,10,4,10,10,4\n',
 '535331,3,1,1,1,3,1,2,1,1,2\n',
 '543558,6,1,3,1,4,5,5,10,1,4\n',
 '555977,5,6,6,8,6,10,4,10,4,4\n',
 '560680,1,1,1,1,2,1,1,1,1,2\n',
 '561477,1,1,1,1,2,1,3,1,1,2\n',
 '563649,8,8,8,1,2,?,6,10,1,4\n',
 '601265,10,4,4,6,2,10,2,3,1,4\n',
 '606140,1,1,1,1,2,?,2,1,1,2\n',
 '606722,5,5,7,8,6,10,7,4,1,4\n',
 '616240,5,3,4,3,4,5,4,7,1,2\n',
 '61634,5,4,3,1,2,?,2,3,1,2\n',
 '625201,8,2,1,1,5,1,1,1,1,2\n',
 '63375,9,1,2,6,4,10,7,7,2,4\n',
 '635844,8,4,10,5,4,4,7,10,1,4\n',
 '636130,1,1,1,1,2,1,3,1,1,2\n',
 '640744,10,10,10,7,9,10,7,10,10,4\n',
 '646904,1,1,1,1,2,1,3,1,1,2\n',
 '653777,8,3,4,9,3,10,3,3,1,4\n',
 '659642,10,8,4,4,4,10,3,10,4,4\n',
 '666090,1,1,1,1,2,1,3,1,1,2\n',
 '666942,1,1,1,1,2,1,3,1,1,2\n',
 '667204,7,8,7,6,4,3,8,8,4,4\n',
 '673637,3,1,1,1,2,5,5,1,1,2\n',
 '684955,2,1,1,1,3,1,2,1,1,2\n',
 '688033,1,1,1,1,2,1,1,1,1,2\n',
 '691628,8,6,4,10,10,1,3,5,1,4\n',
 '693702,1,1,1,1,2,1,1,1,1,2\n',
 '704097,1,1,1,1,1,1,2,1,1,2\n',
 '704168,4,6,5,6,7,?,4,9,1,2\n',
 '706426,5,5,5,2,5,10,4,3,1,4\n',
 '709287,6,8,7,8,6,8,8,9,1,4\n',
 '718641,1,1,1,1,5,1,3,1,1,2\n',
 '721482,4,4,4,4,6,5,7,3,1,2\n',
 '730881,7,6,3,2,5,10,7,4,6,4\n',
 '733639,3,1,1,1,2,?,3,1,1,2\n',
 '733639,3,1,1,1,2,1,3,1,1,2\n',
 '733823,5,4,6,10,2,10,4,1,1,4\n',
 '740492,1,1,1,1,2,1,3,1,1,2\n',
 '743348,3,2,2,1,2,1,2,3,1,2\n',
 '752904,10,1,1,1,2,10,5,4,1,4\n',
 '756136,1,1,1,1,2,1,2,1,1,2\n',
 '760001,8,10,3,2,6,4,3,10,1,4\n',
 '760239,10,4,6,4,5,10,7,1,1,4\n',
 '76389,10,4,7,2,2,8,6,1,1,4\n',
 '764974,5,1,1,1,2,1,3,1,2,2\n',
 '770066,5,2,2,2,2,1,2,2,1,2\n',
 '785208,5,4,6,6,4,10,4,3,1,4\n',
 '785615,8,6,7,3,3,10,3,4,2,4\n',
 '792744,1,1,1,1,2,1,1,1,1,2\n',
 '797327,6,5,5,8,4,10,3,4,1,4\n',
 '798429,1,1,1,1,2,1,3,1,1,2\n',
 '704097,1,1,1,1,1,1,2,1,1,2\n',
 '806423,8,5,5,5,2,10,4,3,1,4\n',
 '809912,10,3,3,1,2,10,7,6,1,4\n',
 '810104,1,1,1,1,2,1,3,1,1,2\n',
 '814265,2,1,1,1,2,1,1,1,1,2\n',
 '814911,1,1,1,1,2,1,1,1,1,2\n',
 '822829,7,6,4,8,10,10,9,5,3,4\n',
 '826923,1,1,1,1,2,1,1,1,1,2\n',
 '830690,5,2,2,2,3,1,1,3,1,2\n',
 '831268,1,1,1,1,1,1,1,3,1,2\n',
 '832226,3,4,4,10,5,1,3,3,1,4\n',
 '832567,4,2,3,5,3,8,7,6,1,4\n',
 '836433,5,1,1,3,2,1,1,1,1,2\n',
 '837082,2,1,1,1,2,1,3,1,1,2\n',
 '846832,3,4,5,3,7,3,4,6,1,2\n',
 '850831,2,7,10,10,7,10,4,9,4,4\n',
 '855524,1,1,1,1,2,1,2,1,1,2\n',
 '857774,4,1,1,1,3,1,2,2,1,2\n',
 '859164,5,3,3,1,3,3,3,3,3,4\n',
 '859350,8,10,10,7,10,10,7,3,8,4\n',
 '866325,8,10,5,3,8,4,4,10,3,4\n',
 '873549,10,3,5,4,3,7,3,5,3,4\n',
 '877291,6,10,10,10,10,10,8,10,10,4\n',
 '877943,3,10,3,10,6,10,5,1,4,4\n',
 '888169,3,2,2,1,4,3,2,1,1,2\n',
 '888523,4,4,4,2,2,3,2,1,1,2\n',
 '896404,2,1,1,1,2,1,3,1,1,2\n',
 '897172,2,1,1,1,2,1,2,1,1,2\n',
 '95719,6,10,10,10,8,10,7,10,7,4\n',
 '160296,5,8,8,10,5,10,8,10,3,4\n',
 '342245,1,1,3,1,2,1,1,1,1,2\n',
 '428598,1,1,3,1,1,1,2,1,1,2\n',
 '492561,4,3,2,1,3,1,2,1,1,2\n',
 '493452,1,1,3,1,2,1,1,1,1,2\n',
 '493452,4,1,2,1,2,1,2,1,1,2\n',
 '521441,5,1,1,2,2,1,2,1,1,2\n',
 '560680,3,1,2,1,2,1,2,1,1,2\n',
 '636437,1,1,1,1,2,1,1,1,1,2\n',
 '640712,1,1,1,1,2,1,2,1,1,2\n',
 '654244,1,1,1,1,1,1,2,1,1,2\n',
 '657753,3,1,1,4,3,1,2,2,1,2\n',
 '685977,5,3,4,1,4,1,3,1,1,2\n',
 '805448,1,1,1,1,2,1,1,1,1,2\n',
 '846423,10,6,3,6,4,10,7,8,4,4\n',
 '1002504,3,2,2,2,2,1,3,2,1,2\n',
 '1022257,2,1,1,1,2,1,1,1,1,2\n',
 '1026122,2,1,1,1,2,1,1,1,1,2\n',
 '1071084,3,3,2,2,3,1,1,2,3,2\n',
 '1080233,7,6,6,3,2,10,7,1,1,4\n',
 '1114570,5,3,3,2,3,1,3,1,1,2\n',
 '1114570,2,1,1,1,2,1,2,2,1,2\n',
 '1116715,5,1,1,1,3,2,2,2,1,2\n',
 '1131411,1,1,1,2,2,1,2,1,1,2\n',
 '1151734,10,8,7,4,3,10,7,9,1,4\n',
 '1156017,3,1,1,1,2,1,2,1,1,2\n',
 '1158247,1,1,1,1,1,1,1,1,1,2\n',
 '1158405,1,2,3,1,2,1,2,1,1,2\n',
 '1168278,3,1,1,1,2,1,2,1,1,2\n',
 '1176187,3,1,1,1,2,1,3,1,1,2\n',
 '1196263,4,1,1,1,2,1,1,1,1,2\n',
 '1196475,3,2,1,1,2,1,2,2,1,2\n',
 '1206314,1,2,3,1,2,1,1,1,1,2\n',
 '1211265,3,10,8,7,6,9,9,3,8,4\n',
 '1213784,3,1,1,1,2,1,1,1,1,2\n',
 '1223003,5,3,3,1,2,1,2,1,1,2\n',
 '1223306,3,1,1,1,2,4,1,1,1,2\n',
 '1223543,1,2,1,3,2,1,1,2,1,2\n',
 '1229929,1,1,1,1,2,1,2,1,1,2\n',
 '1231853,4,2,2,1,2,1,2,1,1,2\n',
 '1234554,1,1,1,1,2,1,2,1,1,2\n',
 '1236837,2,3,2,2,2,2,3,1,1,2\n',
 '1237674,3,1,2,1,2,1,2,1,1,2\n',
 '1238021,1,1,1,1,2,1,2,1,1,2\n',
 '1238464,1,1,1,1,1,?,2,1,1,2\n',
 '1238633,10,10,10,6,8,4,8,5,1,4\n',
 '1238915,5,1,2,1,2,1,3,1,1,2\n',
 '1238948,8,5,6,2,3,10,6,6,1,4\n',
 '1239232,3,3,2,6,3,3,3,5,1,2\n',
 '1239347,8,7,8,5,10,10,7,2,1,4\n',
 '1239967,1,1,1,1,2,1,2,1,1,2\n',
 '1240337,5,2,2,2,2,2,3,2,2,2\n',
 '1253505,2,3,1,1,5,1,1,1,1,2\n',
 '1255384,3,2,2,3,2,3,3,1,1,2\n',
 '1257200,10,10,10,7,10,10,8,2,1,4\n',
 '1257648,4,3,3,1,2,1,3,3,1,2\n',
 '1257815,5,1,3,1,2,1,2,1,1,2\n',
 '1257938,3,1,1,1,2,1,1,1,1,2\n',
 '1258549,9,10,10,10,10,10,10,10,1,4\n',
 '1258556,5,3,6,1,2,1,1,1,1,2\n',
 '1266154,8,7,8,2,4,2,5,10,1,4\n',
 '1272039,1,1,1,1,2,1,2,1,1,2\n',
 '1276091,2,1,1,1,2,1,2,1,1,2\n',
 '1276091,1,3,1,1,2,1,2,2,1,2\n',
 '1276091,5,1,1,3,4,1,3,2,1,2\n',
 '1277629,5,1,1,1,2,1,2,2,1,2\n',
 '1293439,3,2,2,3,2,1,1,1,1,2\n',
 '1293439,6,9,7,5,5,8,4,2,1,2\n',
 '1294562,10,8,10,1,3,10,5,1,1,4\n',
 '1295186,10,10,10,1,6,1,2,8,1,4\n',
 '527337,4,1,1,1,2,1,1,1,1,2\n',
 '558538,4,1,3,3,2,1,1,1,1,2\n',
 '566509,5,1,1,1,2,1,1,1,1,2\n',
 '608157,10,4,3,10,4,10,10,1,1,4\n',
 '677910,5,2,2,4,2,4,1,1,1,2\n',
 '734111,1,1,1,3,2,3,1,1,1,2\n',
 '734111,1,1,1,1,2,2,1,1,1,2\n',
 '780555,5,1,1,6,3,1,2,1,1,2\n',
 '827627,2,1,1,1,2,1,1,1,1,2\n',
 '1049837,1,1,1,1,2,1,1,1,1,2\n',
 '1058849,5,1,1,1,2,1,1,1,1,2\n',
 '1182404,1,1,1,1,1,1,1,1,1,2\n',
 '1193544,5,7,9,8,6,10,8,10,1,4\n',
 '1201870,4,1,1,3,1,1,2,1,1,2\n',
 '1202253,5,1,1,1,2,1,1,1,1,2\n',
 '1227081,3,1,1,3,2,1,1,1,1,2\n',
 '1230994,4,5,5,8,6,10,10,7,1,4\n',
 '1238410,2,3,1,1,3,1,1,1,1,2\n',
 '1246562,10,2,2,1,2,6,1,1,2,4\n',
 '1257470,10,6,5,8,5,10,8,6,1,4\n',
 '1259008,8,8,9,6,6,3,10,10,1,4\n',
 '1266124,5,1,2,1,2,1,1,1,1,2\n',
 '1267898,5,1,3,1,2,1,1,1,1,2\n',
 '1268313,5,1,1,3,2,1,1,1,1,2\n',
 '1268804,3,1,1,1,2,5,1,1,1,2\n',
 '1276091,6,1,1,3,2,1,1,1,1,2\n',
 '1280258,4,1,1,1,2,1,1,2,1,2\n',
 '1293966,4,1,1,1,2,1,1,1,1,2\n',
 '1296572,10,9,8,7,6,4,7,10,3,4\n',
 '1298416,10,6,6,2,4,10,9,7,1,4\n',
 '1299596,6,6,6,5,4,10,7,6,2,4\n',
 '1105524,4,1,1,1,2,1,1,1,1,2\n',
 '1181685,1,1,2,1,2,1,2,1,1,2\n',
 '1211594,3,1,1,1,1,1,2,1,1,2\n',
 '1238777,6,1,1,3,2,1,1,1,1,2\n',
 '1257608,6,1,1,1,1,1,1,1,1,2\n',
 '1269574,4,1,1,1,2,1,1,1,1,2\n',
 '1277145,5,1,1,1,2,1,1,1,1,2\n',
 '1287282,3,1,1,1,2,1,1,1,1,2\n',
 '1296025,4,1,2,1,2,1,1,1,1,2\n',
 '1296263,4,1,1,1,2,1,1,1,1,2\n',
 '1296593,5,2,1,1,2,1,1,1,1,2\n',
 '1299161,4,8,7,10,4,10,7,5,1,4\n',
 '1301945,5,1,1,1,1,1,1,1,1,2\n',
 '1302428,5,3,2,4,2,1,1,1,1,2\n',
 '1318169,9,10,10,10,10,5,10,10,10,4\n',
 '474162,8,7,8,5,5,10,9,10,1,4\n',
 '787451,5,1,2,1,2,1,1,1,1,2\n',
 '1002025,1,1,1,3,1,3,1,1,1,2\n',
 '1070522,3,1,1,1,1,1,2,1,1,2\n',
 '1073960,10,10,10,10,6,10,8,1,5,4\n',
 '1076352,3,6,4,10,3,3,3,4,1,4\n',
 '1084139,6,3,2,1,3,4,4,1,1,4\n',
 '1115293,1,1,1,1,2,1,1,1,1,2\n',
 '1119189,5,8,9,4,3,10,7,1,1,4\n',
 '1133991,4,1,1,1,1,1,2,1,1,2\n',
 '1142706,5,10,10,10,6,10,6,5,2,4\n',
 '1155967,5,1,2,10,4,5,2,1,1,2\n',
 '1170945,3,1,1,1,1,1,2,1,1,2\n',
 '1181567,1,1,1,1,1,1,1,1,1,2\n',
 '1182404,4,2,1,1,2,1,1,1,1,2\n',
 '1204558,4,1,1,1,2,1,2,1,1,2\n',
 '1217952,4,1,1,1,2,1,2,1,1,2\n',
 '1224565,6,1,1,1,2,1,3,1,1,2\n',
 '1238186,4,1,1,1,2,1,2,1,1,2\n',
 '1253917,4,1,1,2,2,1,2,1,1,2\n',
 '1265899,4,1,1,1,2,1,3,1,1,2\n',
 '1268766,1,1,1,1,2,1,1,1,1,2\n',
 '1277268,3,3,1,1,2,1,1,1,1,2\n',
 '1286943,8,10,10,10,7,5,4,8,7,4\n',
 '1295508,1,1,1,1,2,4,1,1,1,2\n',
 '1297327,5,1,1,1,2,1,1,1,1,2\n',
 '1297522,2,1,1,1,2,1,1,1,1,2\n',
 '1298360,1,1,1,1,2,1,1,1,1,2\n',
 '1299924,5,1,1,1,2,1,2,1,1,2\n',
 '1299994,5,1,1,1,2,1,1,1,1,2\n',
 '1304595,3,1,1,1,1,1,2,1,1,2\n',
 '1306282,6,6,7,10,3,10,8,10,2,4\n',
 '1313325,4,10,4,7,3,10,9,10,1,4\n',
 '1320077,1,1,1,1,1,1,1,1,1,2\n',
 '1320077,1,1,1,1,1,1,2,1,1,2\n',
 '1320304,3,1,2,2,2,1,1,1,1,2\n',
 '1330439,4,7,8,3,4,10,9,1,1,4\n',
 '333093,1,1,1,1,3,1,1,1,1,2\n',
 '369565,4,1,1,1,3,1,1,1,1,2\n',
 '412300,10,4,5,4,3,5,7,3,1,4\n',
 '672113,7,5,6,10,4,10,5,3,1,4\n',
 '749653,3,1,1,1,2,1,2,1,1,2\n',
 '769612,3,1,1,2,2,1,1,1,1,2\n',
 '769612,4,1,1,1,2,1,1,1,1,2\n',
 '798429,4,1,1,1,2,1,3,1,1,2\n',
 '807657,6,1,3,2,2,1,1,1,1,2\n',
 '8233704,4,1,1,1,1,1,2,1,1,2\n',
 '837480,7,4,4,3,4,10,6,9,1,4\n',
 '867392,4,2,2,1,2,1,2,1,1,2\n',
 '869828,1,1,1,1,1,1,3,1,1,2\n',
 '1043068,3,1,1,1,2,1,2,1,1,2\n',
 '1056171,2,1,1,1,2,1,2,1,1,2\n',
 '1061990,1,1,3,2,2,1,3,1,1,2\n',
 '1113061,5,1,1,1,2,1,3,1,1,2\n',
 '1116192,5,1,2,1,2,1,3,1,1,2\n',
 '1135090,4,1,1,1,2,1,2,1,1,2\n',
 '1145420,6,1,1,1,2,1,2,1,1,2\n',
 '1158157,5,1,1,1,2,2,2,1,1,2\n',
 '1171578,3,1,1,1,2,1,1,1,1,2\n',
 '1174841,5,3,1,1,2,1,1,1,1,2\n',
 '1184586,4,1,1,1,2,1,2,1,1,2\n',
 '1186936,2,1,3,2,2,1,2,1,1,2\n',
 '1197527,5,1,1,1,2,1,2,1,1,2\n',
 '1222464,6,10,10,10,4,10,7,10,1,4\n',
 '1240603,2,1,1,1,1,1,1,1,1,2\n',
 '1240603,3,1,1,1,1,1,1,1,1,2\n',
 '1241035,7,8,3,7,4,5,7,8,2,4\n',
 '1287971,3,1,1,1,2,1,2,1,1,2\n',
 '1289391,1,1,1,1,2,1,3,1,1,2\n',
 '1299924,3,2,2,2,2,1,4,2,1,2\n',
 '1306339,4,4,2,1,2,5,2,1,2,2\n',
 '1313658,3,1,1,1,2,1,1,1,1,2\n',
 '1313982,4,3,1,1,2,1,4,8,1,2\n',
 '1321264,5,2,2,2,1,1,2,1,1,2\n',
 '1321321,5,1,1,3,2,1,1,1,1,2\n',
 '1321348,2,1,1,1,2,1,2,1,1,2\n',
 '1321931,5,1,1,1,2,1,2,1,1,2\n',
 '1321942,5,1,1,1,2,1,3,1,1,2\n',
 '1321942,5,1,1,1,2,1,3,1,1,2\n',
 '1328331,1,1,1,1,2,1,3,1,1,2\n',
 '1328755,3,1,1,1,2,1,2,1,1,2\n',
 '1331405,4,1,1,1,2,1,3,2,1,2\n',
 '1331412,5,7,10,10,5,10,10,10,1,4\n',
 '1333104,3,1,2,1,2,1,3,1,1,2\n',
 '1334071,4,1,1,1,2,3,2,1,1,2\n',
 '1343068,8,4,4,1,6,10,2,5,2,4\n',
 '1343374,10,10,8,10,6,5,10,3,1,4\n',
 '1344121,8,10,4,4,8,10,8,2,1,4\n',
 '142932,7,6,10,5,3,10,9,10,2,4\n',
 '183936,3,1,1,1,2,1,2,1,1,2\n',
 '324382,1,1,1,1,2,1,2,1,1,2\n',
 '378275,10,9,7,3,4,2,7,7,1,4\n',
 '385103,5,1,2,1,2,1,3,1,1,2\n',
 '690557,5,1,1,1,2,1,2,1,1,2\n',
 '695091,1,1,1,1,2,1,2,1,1,2\n',
 '695219,1,1,1,1,2,1,2,1,1,2\n',
 '824249,1,1,1,1,2,1,3,1,1,2\n',
 '871549,5,1,2,1,2,1,2,1,1,2\n',
 '878358,5,7,10,6,5,10,7,5,1,4\n',
 '1107684,6,10,5,5,4,10,6,10,1,4\n',
 '1115762,3,1,1,1,2,1,1,1,1,2\n',
 '1217717,5,1,1,6,3,1,1,1,1,2\n',
 '1239420,1,1,1,1,2,1,1,1,1,2\n',
 '1254538,8,10,10,10,6,10,10,10,1,4\n',
 '1261751,5,1,1,1,2,1,2,2,1,2\n',
 '1268275,9,8,8,9,6,3,4,1,1,4\n',
 '1272166,5,1,1,1,2,1,1,1,1,2\n',
 '1294261,4,10,8,5,4,1,10,1,1,4\n',
 '1295529,2,5,7,6,4,10,7,6,1,4\n',
 '1298484,10,3,4,5,3,10,4,1,1,4\n',
 '1311875,5,1,2,1,2,1,1,1,1,2\n',
 '1315506,4,8,6,3,4,10,7,1,1,4\n',
 '1320141,5,1,1,1,2,1,2,1,1,2\n',
 '1325309,4,1,2,1,2,1,2,1,1,2\n',
 '1333063,5,1,3,1,2,1,3,1,1,2\n',
 '1333495,3,1,1,1,2,1,2,1,1,2\n',
 '1334659,5,2,4,1,1,1,1,1,1,2\n',
 '1336798,3,1,1,1,2,1,2,1,1,2\n',
 '1344449,1,1,1,1,1,1,2,1,1,2\n',
 '1350568,4,1,1,1,2,1,2,1,1,2\n',
 '1352663,5,4,6,8,4,1,8,10,1,4\n',
 '188336,5,3,2,8,5,10,8,1,2,4\n',
 '352431,10,5,10,3,5,8,7,8,3,4\n',
 '353098,4,1,1,2,2,1,1,1,1,2\n',
 '411453,1,1,1,1,2,1,1,1,1,2\n',
 '557583,5,10,10,10,10,10,10,1,1,4\n',
 '636375,5,1,1,1,2,1,1,1,1,2\n',
 '736150,10,4,3,10,3,10,7,1,2,4\n',
 '803531,5,10,10,10,5,2,8,5,1,4\n',
 '822829,8,10,10,10,6,10,10,10,10,4\n',
 '1016634,2,3,1,1,2,1,2,1,1,2\n',
 '1031608,2,1,1,1,1,1,2,1,1,2\n',
 '1041043,4,1,3,1,2,1,2,1,1,2\n',
 '1042252,3,1,1,1,2,1,2,1,1,2\n',
 '1057067,1,1,1,1,1,?,1,1,1,2\n',
 '1061990,4,1,1,1,2,1,2,1,1,2\n',
 '1073836,5,1,1,1,2,1,2,1,1,2\n',
 '1083817,3,1,1,1,2,1,2,1,1,2\n',
 '1096352,6,3,3,3,3,2,6,1,1,2\n',
 '1140597,7,1,2,3,2,1,2,1,1,2\n',
 '1149548,1,1,1,1,2,1,1,1,1,2\n',
 '1174009,5,1,1,2,1,1,2,1,1,2\n',
 '1183596,3,1,3,1,3,4,1,1,1,2\n',
 '1190386,4,6,6,5,7,6,7,7,3,4\n',
 '1190546,2,1,1,1,2,5,1,1,1,2\n',
 '1213273,2,1,1,1,2,1,1,1,1,2\n',
 '1218982,4,1,1,1,2,1,1,1,1,2\n',
 '1225382,6,2,3,1,2,1,1,1,1,2\n',
 '1235807,5,1,1,1,2,1,2,1,1,2\n',
 '1238777,1,1,1,1,2,1,1,1,1,2\n',
 '1253955,8,7,4,4,5,3,5,10,1,4\n',
 '1257366,3,1,1,1,2,1,1,1,1,2\n',
 '1260659,3,1,4,1,2,1,1,1,1,2\n',
 '1268952,10,10,7,8,7,1,10,10,3,4\n',
 '1275807,4,2,4,3,2,2,2,1,1,2\n',
 '1277792,4,1,1,1,2,1,1,1,1,2\n',
 '1277792,5,1,1,3,2,1,1,1,1,2\n',
 '1285722,4,1,1,3,2,1,1,1,1,2\n',
 '1288608,3,1,1,1,2,1,2,1,1,2\n',
 '1290203,3,1,1,1,2,1,2,1,1,2\n',
 '1294413,1,1,1,1,2,1,1,1,1,2\n',
 '1299596,2,1,1,1,2,1,1,1,1,2\n',
 '1303489,3,1,1,1,2,1,2,1,1,2\n',
 '1311033,1,2,2,1,2,1,1,1,1,2\n',
 '1311108,1,1,1,3,2,1,1,1,1,2\n',
 '1315807,5,10,10,10,10,2,10,10,10,4\n',
 '1318671,3,1,1,1,2,1,2,1,1,2\n',
 '1319609,3,1,1,2,3,4,1,1,1,2\n',
 '1323477,1,2,1,3,2,1,2,1,1,2\n',
 '1324572,5,1,1,1,2,1,2,2,1,2\n',
 '1324681,4,1,1,1,2,1,2,1,1,2\n',
 '1325159,3,1,1,1,2,1,3,1,1,2\n',
 '1326892,3,1,1,1,2,1,2,1,1,2\n',
 '1330361,5,1,1,1,2,1,2,1,1,2\n',
 '1333877,5,4,5,1,8,1,3,6,1,2\n',
 '1334015,7,8,8,7,3,10,7,2,3,4\n',
 '1334667,1,1,1,1,2,1,1,1,1,2\n',
 '1339781,1,1,1,1,2,1,2,1,1,2\n',
 '1339781,4,1,1,1,2,1,3,1,1,2\n',
 '13454352,1,1,3,1,2,1,2,1,1,2\n',
 '1345452,1,1,3,1,2,1,2,1,1,2\n',
 '1345593,3,1,1,3,2,1,2,1,1,2\n',
 '1347749,1,1,1,1,2,1,1,1,1,2\n',
 '1347943,5,2,2,2,2,1,1,1,2,2\n',
 '1348851,3,1,1,1,2,1,3,1,1,2\n',
 '1350319,5,7,4,1,6,1,7,10,3,4\n',
 '1350423,5,10,10,8,5,5,7,10,1,4\n',
 '1352848,3,10,7,8,5,8,7,4,1,4\n',
 '1353092,3,2,1,2,2,1,3,1,1,2\n',
 '1354840,2,1,1,1,2,1,3,1,1,2\n',
 '1354840,5,3,2,1,3,1,1,1,1,2\n',
 '1355260,1,1,1,1,2,1,2,1,1,2\n',
 '1365075,4,1,4,1,2,1,1,1,1,2\n',
 '1365328,1,1,2,1,2,1,2,1,1,2\n',
 '1368267,5,1,1,1,2,1,1,1,1,2\n',
 '1368273,1,1,1,1,2,1,1,1,1,2\n',
 '1368882,2,1,1,1,2,1,1,1,1,2\n',
 '1369821,10,10,10,10,5,10,10,10,7,4\n',
 '1371026,5,10,10,10,4,10,5,6,3,4\n',
 '1371920,5,1,1,1,2,1,3,2,1,2\n',
 '466906,1,1,1,1,2,1,1,1,1,2\n',
 '466906,1,1,1,1,2,1,1,1,1,2\n',
 '534555,1,1,1,1,2,1,1,1,1,2\n',
 '536708,1,1,1,1,2,1,1,1,1,2\n',
 '566346,3,1,1,1,2,1,2,3,1,2\n',
 '603148,4,1,1,1,2,1,1,1,1,2\n',
 '654546,1,1,1,1,2,1,1,1,8,2\n',
 '654546,1,1,1,3,2,1,1,1,1,2\n',
 '695091,5,10,10,5,4,5,4,4,1,4\n',
 '714039,3,1,1,1,2,1,1,1,1,2\n',
 '763235,3,1,1,1,2,1,2,1,2,2\n',
 '776715,3,1,1,1,3,2,1,1,1,2\n',
 '841769,2,1,1,1,2,1,1,1,1,2\n',
 '888820,5,10,10,3,7,3,8,10,2,4\n',
 '897471,4,8,6,4,3,4,10,6,1,4\n',
 '897471,4,8,8,5,4,5,10,4,1,4']


In [3]:
import numpy as np
#processing data
data2 = [ r.strip().split(',') for r in data] 
# ignore cases with missings
data3= [ L for L in data2 if L.count('?')==0]
# converting to matrix
data= np.array(data3, dtype=np.float64)      



In [4]:
n,m = data.shape
X   = data[:,1:m-2]
Y   = data[:,m-1]
Y[(Y==2)]=1.0
Y[(Y==4)]=-1.0

In [31]:
"""
two layers with tanh as activation functions
Cost function is the SSE

"""


class layer:
    def __init__(self, n_nodes, n_inputs):
        self.n_nodes  = n_nodes
        self.n_inputs = n_inputs
        self.w = 2*np.random.random([n_nodes, n_inputs])-1
    def feed(self,x):
        return  np.tanh(np.dot(self.w,x.reshape(-1,1)))
    def feedData(self,X):
        d = np.dot(X,self.w.T)
        return np.tanh(d)
    
eta  = 0.01    
n_nodes = 20             
in_dim = X.shape[1]
np.random.seed(234) 
L1    = layer(n_nodes ,in_dim)
L2    = layer(1, n_nodes)
iters = 1000
SSE = np.Infinity
for i in range(iters):    
    err  = [] 
    for obs in range(X.shape[0]):
        o0 = X[obs,:]
        o1 = L1.feed(o0)
        o2 = float(L2.feed(o1))
        
        y = float(Y[obs])
        dE_do2 = -(y-o2)
        
        err.append(y-o2)
        delta2 = dE_do2*(1-o2*o2)
        L2.w  += -eta*delta2*o1.reshape(1,-1)
            
        delta1 = delta2*(1-o1*o1)    
        L1.w += -eta*delta1*o0
    SSE0 = SSE    
    SSE  = np.dot(err,err)    
    if SSE>SSE0 and i>50: 
        break    
    print("epoch = ",i," SSE =",SSE)
    

O1    = L1.feedData(X)
O2    = L2.feedData(O1)
pred  = O2.copy()
pred[pred<0]=-1
pred[pred>0]=1
    

acc = sum([pred[i]!=Y[i] for i in range(len(Y))])/len(Y)
print("\ntrain acc =",float(acc))

from sklearn.metrics import precision_recall_fscore_support, confusion_matrix 
conf = confusion_matrix(Y, pred) 
confMat = conf[0], conf[1]    
[TN, FN], [FP, TP] = confMat
print('TN,  FN,  FP,  TP')
print(TN,  FN,  FP,  TP)

import sklearn.metrics as sk
fpr, tpr, thresholds = sk.roc_curve(Y, pred)
auroc = sk.auc(fpr, tpr)


epoch =  0  SSE = 354.715947871
epoch =  1  SSE = 278.991645655
epoch =  2  SSE = 262.771076532
epoch =  3  SSE = 236.92930051
epoch =  4  SSE = 229.508767676
epoch =  5  SSE = 247.59341988
epoch =  6  SSE = 208.657733137
epoch =  7  SSE = 198.120101243
epoch =  8  SSE = 188.461556632
epoch =  9  SSE = 178.410321398
epoch =  10  SSE = 177.096275446
epoch =  11  SSE = 166.078733463
epoch =  12  SSE = 156.648011312
epoch =  13  SSE = 164.800902364
epoch =  14  SSE = 154.401349812
epoch =  15  SSE = 147.08303724
epoch =  16  SSE = 135.990454213
epoch =  17  SSE = 133.549723573
epoch =  18  SSE = 141.811663597
epoch =  19  SSE = 135.027045666
epoch =  20  SSE = 129.390574258
epoch =  21  SSE = 124.925361241
epoch =  22  SSE = 118.998287519
epoch =  23  SSE = 109.856923461
epoch =  24  SSE = 112.430880632
epoch =  25  SSE = 108.75145727
epoch =  26  SSE = 107.573014749
epoch =  27  SSE = 111.914083589
epoch =  28  SSE = 101.47470085
epoch =  29  SSE = 100.136739447
epoch =  30  SSE = 115.30

In [27]:
acc

[array([False], dtype=bool),
 array([ True], dtype=bool),
 array([False], dtype=bool),
 array([ True], dtype=bool),
 array([False], dtype=bool),
 array([False], dtype=bool),
 array([False], dtype=bool),
 array([False], dtype=bool),
 array([False], dtype=bool),
 array([False], dtype=bool),
 array([False], dtype=bool),
 array([False], dtype=bool),
 array([False], dtype=bool),
 array([False], dtype=bool),
 array([False], dtype=bool),
 array([ True], dtype=bool),
 array([False], dtype=bool),
 array([False], dtype=bool),
 array([False], dtype=bool),
 array([False], dtype=bool),
 array([False], dtype=bool),
 array([False], dtype=bool),
 array([False], dtype=bool),
 array([False], dtype=bool),
 array([False], dtype=bool),
 array([False], dtype=bool),
 array([False], dtype=bool),
 array([False], dtype=bool),
 array([False], dtype=bool),
 array([False], dtype=bool),
 array([False], dtype=bool),
 array([False], dtype=bool),
 array([False], dtype=bool),
 array([False], dtype=bool),
 array([False]