In [2]:
import tensorflow as tf

/home/ks/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


In [11]:
a  = tf.placeholder(tf.float32,[None,1]) # None means anything 
b  = tf.placeholder(tf.float32,[None,1])
addOp = tf.add(a,b)

import numpy as np


aL = np.random.rand(10).reshape(-1,1)
bL = np.random.rand(10).reshape(-1,1)

s1 = tf.truncated_normal([10,1])
s2 = tf.truncated_normal([1,10])

# only calculated when used
sd =  tf.truncated_normal([10,2])

with tf.Session() as sess:
    result = sess.run(addOp, feed_dict={ a : aL, b:bL})
    res2   = sess.run(tf.matmul(s2,s1))    
    print(result)
    print(res2)
    print('printing the same variable after two runs')
    print(sess.run(sd))
    print(sess.run(sd))
    





[[ 1.74368548]
 [ 0.90936047]
 [ 0.94269347]
 [ 1.63919485]
 [ 0.971223  ]
 [ 0.46693841]
 [ 0.40761134]
 [ 0.58708692]
 [ 1.4677974 ]
 [ 1.31219661]]
[[ 3.87904811]]
printing the same variable after two runs
[[-0.55271429 -1.80957627]
 [-1.64568281 -0.02021232]
 [-0.9438383   0.0363254 ]
 [-0.25255147  0.62427413]
 [ 0.09781359  0.53088272]
 [-1.8658514   0.21195127]
 [-0.47678873  1.81250751]
 [ 1.4436115  -0.67786157]
 [ 0.23039345  1.20555818]
 [ 0.75145549 -0.33561099]]
[[ 0.15142274  0.4461107 ]
 [ 0.57741261 -1.1626339 ]
 [ 1.2888099  -0.6743753 ]
 [-0.13608971 -1.40111732]
 [-0.32007334 -0.4764328 ]
 [-1.26314592 -0.71676761]
 [-1.0868814   0.95370036]
 [-0.82541972 -0.41105932]
 [-0.27998292  0.59359968]
 [ 0.25822353 -0.07517246]]


In [10]:
a = np.random.random([10,2])
print(a)
c = np.argmax(a,1)
print(c)

[[ 0.61413459  0.46816803]
 [ 0.75946724  0.6737025 ]
 [ 0.71929158  0.58476569]
 [ 0.17112277  0.52112685]
 [ 0.66653512  0.45814956]
 [ 0.05882607  0.97337028]
 [ 0.5873768   0.04208344]
 [ 0.87661174  0.35136861]
 [ 0.94950419  0.99113695]
 [ 0.34342125  0.58732046]]
[0 0 0 1 0 1 0 0 1 1]


# Simple linear model 

In [28]:
w = tf.Variable([3.0],tf.float32)
b = tf.Variable([1.0],tf.float32)

x = tf.placeholder(tf.float32)

d = np.random.rand(10)


model = w*x+b

init = tf.global_variables_initializer()

with tf.Session() as ses:
    ses.run(init)
    print(ses.run(model, feed_dict={x:d}))
    
print('just verifying...')    
print(3*d+t1)
    

[ 1.87388134  3.25264978  3.2553997   3.6243782   1.63384736  1.80692542
  2.06495643  1.8482095   2.6851759   3.89874339]

[ 1.87388128  3.25264961  3.25539961  3.62437828  1.63384732  1.80692539
  2.06495643  1.84820953  2.68517603  3.89874346]


In [52]:
y = tf.placeholder(tf.float32)
 
# creating  noisy target, the true parms ar 2,-3 
yd = 2*d - 3 + 0.2*np.random.rand(len(d)) 

#loss
loss = tf.reduce_sum(tf.squared_difference(y,model))

#train
train = tf.train.GradientDescentOptimizer(0.01).minimize(loss)

with tf.Session() as ses:
    ses.run(init)
    for i in range(2000):
        ses.run(train, feed_dict={x:d, y:yd})
        cost = ses.run(loss, feed_dict={x:d, y:yd})
        print('epoch=',i,cost,ses.run([w,b]))
   
  

epoch= 0 188.055 [array([ 2.95144129], dtype=float32), array([ 0.91110235], dtype=float32)]
epoch= 1 178.447 [array([ 2.90417242], dtype=float32), array([ 0.82449877], dtype=float32)]
epoch= 2 169.331 [array([ 2.85815978], dtype=float32), array([ 0.74012971], dtype=float32)]
epoch= 3 160.683 [array([ 2.8133707], dtype=float32), array([ 0.65793717], dtype=float32)]
epoch= 4 152.479 [array([ 2.76977348], dtype=float32), array([ 0.57786453], dtype=float32)]
epoch= 5 144.695 [array([ 2.72733712], dtype=float32), array([ 0.49985677], dtype=float32)]
epoch= 6 137.311 [array([ 2.68603134], dtype=float32), array([ 0.42386025], dtype=float32)]
epoch= 7 130.305 [array([ 2.64582658], dtype=float32), array([ 0.3498227], dtype=float32)]
epoch= 8 123.659 [array([ 2.60669446], dtype=float32), array([ 0.27769327], dtype=float32)]
epoch= 9 117.353 [array([ 2.56860685], dtype=float32), array([ 0.20742238], dtype=float32)]
epoch= 10 111.371 [array([ 2.53153682], dtype=float32), array([ 0.13896175], dtype

epoch= 94 1.95396 [array([ 1.34635937], dtype=float32), array([-2.17559457], dtype=float32)]
epoch= 95 1.88453 [array([ 1.34330046], dtype=float32), array([-2.18340302], dtype=float32)]
epoch= 96 1.81859 [array([ 1.34034634], dtype=float32), array([-2.19102287], dtype=float32)]
epoch= 97 1.75597 [array([ 1.33749413], dtype=float32), array([-2.19845891], dtype=float32)]
epoch= 98 1.69649 [array([ 1.33474123], dtype=float32), array([-2.20571589], dtype=float32)]
epoch= 99 1.64 [array([ 1.33208501], dtype=float32), array([-2.21279836], dtype=float32)]
epoch= 100 1.58634 [array([ 1.32952297], dtype=float32), array([-2.21971107], dtype=float32)]
epoch= 101 1.53537 [array([ 1.32705259], dtype=float32), array([-2.22645831], dtype=float32)]
epoch= 102 1.48694 [array([ 1.32467151], dtype=float32), array([-2.23304439], dtype=float32)]
epoch= 103 1.44094 [array([ 1.32237732], dtype=float32), array([-2.23947334], dtype=float32)]
epoch= 104 1.39723 [array([ 1.32016778], dtype=float32), array([-2.24

epoch= 235 0.463338 [array([ 1.32589316], dtype=float32), array([-2.52189851], dtype=float32)]
epoch= 236 0.462308 [array([ 1.32666063], dtype=float32), array([-2.52256346], dtype=float32)]
epoch= 237 0.461282 [array([ 1.32742977], dtype=float32), array([-2.52322316], dtype=float32)]
epoch= 238 0.460261 [array([ 1.32820046], dtype=float32), array([-2.52387786], dtype=float32)]
epoch= 239 0.459243 [array([ 1.32897258], dtype=float32), array([-2.52452755], dtype=float32)]
epoch= 240 0.45823 [array([ 1.32974613], dtype=float32), array([-2.52517247], dtype=float32)]
epoch= 241 0.45722 [array([ 1.33052111], dtype=float32), array([-2.52581286], dtype=float32)]
epoch= 242 0.456214 [array([ 1.3312974], dtype=float32), array([-2.52644873], dtype=float32)]
epoch= 243 0.455212 [array([ 1.33207488], dtype=float32), array([-2.52708006], dtype=float32)]
epoch= 244 0.454214 [array([ 1.33285356], dtype=float32), array([-2.5277071], dtype=float32)]
epoch= 245 0.453219 [array([ 1.33363342], dtype=float3

epoch= 367 0.349346 [array([ 1.42863512], dtype=float32), array([-2.58841944], dtype=float32)]
epoch= 368 0.34861 [array([ 1.42937994], dtype=float32), array([-2.58884597], dtype=float32)]
epoch= 369 0.347875 [array([ 1.43012404], dtype=float32), array([-2.58927178], dtype=float32)]
epoch= 370 0.347142 [array([ 1.43086743], dtype=float32), array([-2.58969712], dtype=float32)]
epoch= 371 0.346411 [array([ 1.43160999], dtype=float32), array([-2.59012175], dtype=float32)]
epoch= 372 0.345681 [array([ 1.43235183], dtype=float32), array([-2.59054589], dtype=float32)]
epoch= 373 0.344953 [array([ 1.43309295], dtype=float32), array([-2.59096932], dtype=float32)]
epoch= 374 0.344227 [array([ 1.43383324], dtype=float32), array([-2.59139228], dtype=float32)]
epoch= 375 0.343502 [array([ 1.43457282], dtype=float32), array([-2.59181452], dtype=float32)]
epoch= 376 0.342779 [array([ 1.43531156], dtype=float32), array([-2.59223628], dtype=float32)]
epoch= 377 0.342057 [array([ 1.43604958], dtype=flo

epoch= 509 0.259679 [array([ 1.52677226], dtype=float32), array([-2.64393663], dtype=float32)]
epoch= 510 0.259144 [array([ 1.52741027], dtype=float32), array([-2.64429593], dtype=float32)]
epoch= 511 0.258609 [array([ 1.52804756], dtype=float32), array([-2.64465475], dtype=float32)]
epoch= 512 0.258076 [array([ 1.52868414], dtype=float32), array([-2.64501333], dtype=float32)]
epoch= 513 0.257543 [array([ 1.52932], dtype=float32), array([-2.64537144], dtype=float32)]
epoch= 514 0.257012 [array([ 1.52995515], dtype=float32), array([-2.64572906], dtype=float32)]
epoch= 515 0.256482 [array([ 1.53058958], dtype=float32), array([-2.64608645], dtype=float32)]
epoch= 516 0.255954 [array([ 1.5312233], dtype=float32), array([-2.64644337], dtype=float32)]
epoch= 517 0.255426 [array([ 1.5318563], dtype=float32), array([-2.6467998], dtype=float32)]
epoch= 518 0.2549 [array([ 1.53248858], dtype=float32), array([-2.647156], dtype=float32)]
epoch= 519 0.254375 [array([ 1.53312016], dtype=float32), ar

epoch= 631 0.202413 [array([ 1.59957004], dtype=float32), array([-2.68492603], dtype=float32)]
epoch= 632 0.202005 [array([ 1.60012662], dtype=float32), array([-2.68523932], dtype=float32)]
epoch= 633 0.201598 [array([ 1.60068262], dtype=float32), array([-2.68555236], dtype=float32)]
epoch= 634 0.201192 [array([ 1.60123801], dtype=float32), array([-2.68586493], dtype=float32)]
epoch= 635 0.200787 [array([ 1.60179281], dtype=float32), array([-2.68617725], dtype=float32)]
epoch= 636 0.200383 [array([ 1.6023469], dtype=float32), array([-2.68648911], dtype=float32)]
epoch= 637 0.19998 [array([ 1.60290039], dtype=float32), array([-2.68680072], dtype=float32)]
epoch= 638 0.199577 [array([ 1.60345328], dtype=float32), array([-2.68711185], dtype=float32)]
epoch= 639 0.199176 [array([ 1.60400558], dtype=float32), array([-2.68742275], dtype=float32)]
epoch= 640 0.198775 [array([ 1.60455728], dtype=float32), array([-2.68773341], dtype=float32)]
epoch= 641 0.198375 [array([ 1.60510826], dtype=floa

epoch= 745 0.161339 [array([ 1.65917528], dtype=float32), array([-2.71848059], dtype=float32)]
epoch= 746 0.161023 [array([ 1.65966523], dtype=float32), array([-2.71875644], dtype=float32)]
epoch= 747 0.160708 [array([ 1.66015458], dtype=float32), array([-2.71903205], dtype=float32)]
epoch= 748 0.160393 [array([ 1.66064346], dtype=float32), array([-2.71930718], dtype=float32)]
epoch= 749 0.160079 [array([ 1.66113174], dtype=float32), array([-2.71958208], dtype=float32)]
epoch= 750 0.159766 [array([ 1.66161942], dtype=float32), array([-2.71985674], dtype=float32)]
epoch= 751 0.159454 [array([ 1.66210663], dtype=float32), array([-2.72013092], dtype=float32)]
epoch= 752 0.159142 [array([ 1.66259325], dtype=float32), array([-2.72040486], dtype=float32)]
epoch= 753 0.158831 [array([ 1.66307938], dtype=float32), array([-2.72067857], dtype=float32)]
epoch= 754 0.158521 [array([ 1.66356492], dtype=float32), array([-2.72095203], dtype=float32)]
epoch= 755 0.158211 [array([ 1.66404998], dtype=fl

epoch= 868 0.127333 [array([ 1.71550369], dtype=float32), array([-2.75019121], dtype=float32)]
epoch= 869 0.127093 [array([ 1.71593058], dtype=float32), array([-2.75043154], dtype=float32)]
epoch= 870 0.126853 [array([ 1.71635699], dtype=float32), array([-2.75067163], dtype=float32)]
epoch= 871 0.126615 [array([ 1.71678293], dtype=float32), array([-2.75091147], dtype=float32)]
epoch= 872 0.126376 [array([ 1.71720839], dtype=float32), array([-2.75115108], dtype=float32)]
epoch= 873 0.126139 [array([ 1.71763337], dtype=float32), array([-2.75139046], dtype=float32)]
epoch= 874 0.125901 [array([ 1.71805787], dtype=float32), array([-2.75162935], dtype=float32)]
epoch= 875 0.125665 [array([ 1.7184819], dtype=float32), array([-2.75186801], dtype=float32)]
epoch= 876 0.125429 [array([ 1.71890545], dtype=float32), array([-2.75210643], dtype=float32)]
epoch= 877 0.125193 [array([ 1.71932852], dtype=float32), array([-2.75234461], dtype=float32)]
epoch= 878 0.124958 [array([ 1.71975112], dtype=flo

epoch= 1026 0.095372 [array([ 1.7773639], dtype=float32), array([-2.78501606], dtype=float32)]
epoch= 1027 0.0952035 [array([ 1.77772164], dtype=float32), array([-2.78521752], dtype=float32)]
epoch= 1028 0.0950355 [array([ 1.77807891], dtype=float32), array([-2.78541875], dtype=float32)]
epoch= 1029 0.0948678 [array([ 1.77843583], dtype=float32), array([-2.78561974], dtype=float32)]
epoch= 1030 0.0947006 [array([ 1.77879238], dtype=float32), array([-2.78582048], dtype=float32)]
epoch= 1031 0.0945336 [array([ 1.77914846], dtype=float32), array([-2.78602099], dtype=float32)]
epoch= 1032 0.094367 [array([ 1.77950418], dtype=float32), array([-2.78622127], dtype=float32)]
epoch= 1033 0.0942008 [array([ 1.77985954], dtype=float32), array([-2.7864213], dtype=float32)]
epoch= 1034 0.0940351 [array([ 1.78021443], dtype=float32), array([-2.78662109], dtype=float32)]
epoch= 1035 0.0938697 [array([ 1.78056896], dtype=float32), array([-2.78682065], dtype=float32)]
epoch= 1036 0.0937046 [array([ 1.7

epoch= 1168 0.0748607 [array([ 1.82435596], dtype=float32), array([-2.81147051], dtype=float32)]
epoch= 1169 0.0747381 [array([ 1.82466114], dtype=float32), array([-2.81164241], dtype=float32)]
epoch= 1170 0.0746158 [array([ 1.82496595], dtype=float32), array([-2.81181407], dtype=float32)]
epoch= 1171 0.0744938 [array([ 1.82527041], dtype=float32), array([-2.81198549], dtype=float32)]
epoch= 1172 0.074372 [array([ 1.82557452], dtype=float32), array([-2.81215668], dtype=float32)]
epoch= 1173 0.0742506 [array([ 1.82587826], dtype=float32), array([-2.81232762], dtype=float32)]
epoch= 1174 0.0741294 [array([ 1.82618177], dtype=float32), array([-2.81249857], dtype=float32)]
epoch= 1175 0.0740084 [array([ 1.82648492], dtype=float32), array([-2.81266928], dtype=float32)]
epoch= 1176 0.0738878 [array([ 1.82678771], dtype=float32), array([-2.81283975], dtype=float32)]
epoch= 1177 0.0737674 [array([ 1.82709014], dtype=float32), array([-2.81300998], dtype=float32)]
epoch= 1178 0.0736473 [array([ 

epoch= 1331 0.0581024 [array([ 1.86984956], dtype=float32), array([-2.83708143], dtype=float32)]
epoch= 1332 0.0580174 [array([ 1.87010384], dtype=float32), array([-2.83722448], dtype=float32)]
epoch= 1333 0.0579325 [array([ 1.87035787], dtype=float32), array([-2.83736753], dtype=float32)]
epoch= 1334 0.0578477 [array([ 1.87061155], dtype=float32), array([-2.83751035], dtype=float32)]
epoch= 1335 0.0577632 [array([ 1.87086499], dtype=float32), array([-2.83765292], dtype=float32)]
epoch= 1336 0.0576789 [array([ 1.87111807], dtype=float32), array([-2.8377955], dtype=float32)]
epoch= 1337 0.0575948 [array([ 1.87137091], dtype=float32), array([-2.83793783], dtype=float32)]
epoch= 1338 0.0575108 [array([ 1.87162352], dtype=float32), array([-2.83807993], dtype=float32)]
epoch= 1339 0.057427 [array([ 1.87187576], dtype=float32), array([-2.83822203], dtype=float32)]
epoch= 1340 0.0573434 [array([ 1.87212777], dtype=float32), array([-2.83836389], dtype=float32)]
epoch= 1341 0.0572601 [array([ 1

epoch= 1466 0.0481767 [array([ 1.90172637], dtype=float32), array([-2.85502696], dtype=float32)]
epoch= 1467 0.0481137 [array([ 1.90194499], dtype=float32), array([-2.85514998], dtype=float32)]
epoch= 1468 0.048051 [array([ 1.90216339], dtype=float32), array([-2.85527301], dtype=float32)]
epoch= 1469 0.0479884 [array([ 1.90238154], dtype=float32), array([-2.85539579], dtype=float32)]
epoch= 1470 0.0479259 [array([ 1.90259945], dtype=float32), array([-2.85551834], dtype=float32)]
epoch= 1471 0.0478635 [array([ 1.90281713], dtype=float32), array([-2.85564089], dtype=float32)]
epoch= 1472 0.0478013 [array([ 1.90303457], dtype=float32), array([-2.8557632], dtype=float32)]
epoch= 1473 0.0477393 [array([ 1.90325177], dtype=float32), array([-2.85588551], dtype=float32)]
epoch= 1474 0.0476773 [array([ 1.90346873], dtype=float32), array([-2.85600758], dtype=float32)]
epoch= 1475 0.0476154 [array([ 1.90368545], dtype=float32), array([-2.85612965], dtype=float32)]
epoch= 1476 0.0475539 [array([ 1

epoch= 1558 0.0429407 [array([ 1.92084849], dtype=float32), array([-2.8657918], dtype=float32)]
epoch= 1559 0.0428896 [array([ 1.92104566], dtype=float32), array([-2.8659029], dtype=float32)]
epoch= 1560 0.0428384 [array([ 1.92124271], dtype=float32), array([-2.86601377], dtype=float32)]
epoch= 1561 0.0427875 [array([ 1.92143953], dtype=float32), array([-2.86612463], dtype=float32)]
epoch= 1562 0.0427366 [array([ 1.9216361], dtype=float32), array([-2.86623526], dtype=float32)]
epoch= 1563 0.0426859 [array([ 1.92183244], dtype=float32), array([-2.86634588], dtype=float32)]
epoch= 1564 0.0426353 [array([ 1.92202854], dtype=float32), array([-2.86645627], dtype=float32)]
epoch= 1565 0.0425847 [array([ 1.9222244], dtype=float32), array([-2.86656666], dtype=float32)]
epoch= 1566 0.0425344 [array([ 1.92242014], dtype=float32), array([-2.86667681], dtype=float32)]
epoch= 1567 0.042484 [array([ 1.92261565], dtype=float32), array([-2.86678696], dtype=float32)]
epoch= 1568 0.0424338 [array([ 1.92

epoch= 1703 0.0365944 [array([ 1.94726098], dtype=float32), array([-2.88066077], dtype=float32)]
epoch= 1704 0.0365574 [array([ 1.9474287], dtype=float32), array([-2.88075519], dtype=float32)]
epoch= 1705 0.0365204 [array([ 1.94759619], dtype=float32), array([-2.8808496], dtype=float32)]
epoch= 1706 0.0364836 [array([ 1.94776344], dtype=float32), array([-2.88094378], dtype=float32)]
epoch= 1707 0.0364469 [array([ 1.94793057], dtype=float32), array([-2.88103795], dtype=float32)]
epoch= 1708 0.0364102 [array([ 1.94809747], dtype=float32), array([-2.88113189], dtype=float32)]
epoch= 1709 0.0363736 [array([ 1.94826424], dtype=float32), array([-2.88122582], dtype=float32)]
epoch= 1710 0.0363371 [array([ 1.94843078], dtype=float32), array([-2.88131952], dtype=float32)]
epoch= 1711 0.0363006 [array([ 1.94859719], dtype=float32), array([-2.88141322], dtype=float32)]
epoch= 1712 0.0362643 [array([ 1.94876337], dtype=float32), array([-2.88150668], dtype=float32)]
epoch= 1713 0.036228 [array([ 1.

epoch= 1825 0.032639 [array([ 1.96639395], dtype=float32), array([-2.89143181], dtype=float32)]
epoch= 1826 0.0326109 [array([ 1.96654022], dtype=float32), array([-2.89151406], dtype=float32)]
epoch= 1827 0.0325828 [array([ 1.96668637], dtype=float32), array([-2.89159632], dtype=float32)]
epoch= 1828 0.0325547 [array([ 1.96683228], dtype=float32), array([-2.89167857], dtype=float32)]
epoch= 1829 0.0325267 [array([ 1.96697807], dtype=float32), array([-2.89176059], dtype=float32)]
epoch= 1830 0.0324988 [array([ 1.96712375], dtype=float32), array([-2.8918426], dtype=float32)]
epoch= 1831 0.032471 [array([ 1.96726918], dtype=float32), array([-2.89192438], dtype=float32)]
epoch= 1832 0.0324432 [array([ 1.9674145], dtype=float32), array([-2.89200616], dtype=float32)]
epoch= 1833 0.0324155 [array([ 1.96755958], dtype=float32), array([-2.89208794], dtype=float32)]
epoch= 1834 0.0323879 [array([ 1.96770453], dtype=float32), array([-2.89216948], dtype=float32)]
epoch= 1835 0.0323602 [array([ 1.9

epoch= 1954 0.0294799 [array([ 1.98397505], dtype=float32), array([-2.90132928], dtype=float32)]
epoch= 1955 0.0294588 [array([ 1.98410165], dtype=float32), array([-2.90140057], dtype=float32)]
epoch= 1956 0.0294377 [array([ 1.98422813], dtype=float32), array([-2.90147185], dtype=float32)]
epoch= 1957 0.0294167 [array([ 1.9843545], dtype=float32), array([-2.9015429], dtype=float32)]
epoch= 1958 0.0293957 [array([ 1.98448074], dtype=float32), array([-2.90161395], dtype=float32)]
epoch= 1959 0.0293748 [array([ 1.98460674], dtype=float32), array([-2.901685], dtype=float32)]
epoch= 1960 0.029354 [array([ 1.98473263], dtype=float32), array([-2.90175581], dtype=float32)]
epoch= 1961 0.0293331 [array([ 1.98485839], dtype=float32), array([-2.90182662], dtype=float32)]
epoch= 1962 0.0293124 [array([ 1.98498404], dtype=float32), array([-2.90189743], dtype=float32)]
epoch= 1963 0.0292916 [array([ 1.98510957], dtype=float32), array([-2.901968], dtype=float32)]
epoch= 1964 0.029271 [array([ 1.98523